package entities;
// Generated 2016-05-13 11:54:52 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Recipes generated by hbm2java
 */
@Entity
@Table(name="RECIPES")
public class Recipes  implements java.io.Serializable {


     private String name;
     private String ingredients;
     private String recipe;

    public Recipes() {
    }

    public Recipes(String name, String ingredients, String recipe) {
       this.name = name;
       this.ingredients = ingredients;
       this.recipe = recipe;
    }
   
     @Id 

    
    @Column(name="NAME", unique=true, nullable=false, length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="INGREDIENTS", nullable=false, length=500)
    public String getIngredients() {
        return this.ingredients;
    }
    
    public void setIngredients(String ingredients) {
        this.ingredients = ingredients;
    }

    
    @Column(name="RECIPE", nullable=false, length=3500)
    public String getRecipe() {
        return this.recipe;
    }
    
    public void setRecipe(String recipe) {
        this.recipe = recipe;
    }




}


